// components/Odontologia/Ortodoncia/constants.js
import { FiFileText, FiTarget, FiLayers, FiEdit3, FiCamera } from 'react-icons/fi';

export const EMPTY_STATE = {
  requiere_tratamiento: false,
  motivo_no_requiere: '',
  diagnostico: {
    motivo_consulta: '',
    historia_medica: '',
    historia_odontologica: '',
    historia_familiar: '',
    craneo: '',
    cara: '',
    musculatura: '',
    atm: '',
    menton: '',
    anl: '',
    fonacion: '',
    deglucion: '',
    respiracion: '',
    permeabilidad_nasal: '',
    habitos: '',
    asimetria_facial: '',
    plano_bipupilar: '',
    tabique_nasal: '',
    comisura_bucales: '',
    filtrum: '',
    desviacion_filtrum: '',
    desviacion_menton: '',
    perfil_ap: '',
    perfil_vertical: '',
    labios: '',
    labio_inferior: '',
    labio_superior: '',
    sonrisa: '',
    mucosa_labio: '',
    mucosa_vestibular: '',
    frenillos_vestibulares: '',
    mucosa_palatina: '',
    mucosa_orofaringea: '',
    amigdalas: '',
    lengua: '',
    gingiva_incisivos_inferiores: '',
    gingiva_general: '',
    arco_superior: '',
    arco_inferior: '',
    error_molar_derecho: '',
    error_molar_izquierdo: '',
    dientes_ausentes: '',
    alteraciones_dientes: '',
    relacion_molar_derecha: '',
    relacion_molar_izquierda: '',
    relacion_canina_derecha: '',
    relacion_canina_izquierda: '',
    mordida_invertida: '',
    resalte_horizontal: '',
    curva_spee: '',
    resalte_vertical: '',
    desviacion_vertical_proceso_alveolar_sup: '',
    mordida_abierta_anterior: '',
    mordida_abierta_posterior: '',
    dimension_transversal_maxilar: '',
    mordida_cruzada_posterior: '',
    altura_cuspide_palatina_sup: '',
    linea_media_superior: '',
    linea_media_inferior: '',
    incisivos_superiores: '',
    incisivos_inferiores: '',
    clase_ii_2: '',
    observaciones: '',
    maloclusion: '',
  },
  trabajo: {
    radiografias: '',
    interconsultas: '',
    informes: '',
    diagnostico_definitivo: '',
    objetivo: '',
  },
  tratamiento: {
    fecha_inicial: '',
    tiempo_estimado: '',
    fecha_final: '',
    tipo: '',
    aparatos_ortopedicos: '',
    anclaje_superior: '',
    anclaje_inferior: '',
    aparatos: '',
    otros: '',
    tecnica: '',
    brackets: '',
    tubos_adhesivos_sup: '',
    tubos_adhesivos_inf: '',
    banda_superior: '',
    banda_inferior: '',
    tubos_soldados_sup: '',
    tubos_soldados_inf: '',
    extracciones: '',
    descripcion: '',
  },
  resumen: {
    doctor: 'Dr. Jefferson Cagua',
    seccion: 'Resumen',
    fecha_inicial: '',
    fecha_final: '',
    tiempo_estimado: '',
    tipo_brackets: '',
    diagnostico: '',
    anclaje_superior: '',
    anclaje_inferior: '',
    nota: '',
  },
  fotografias: [],
};

export const TABS = [
  { id: 'diagnostico', label: 'Examen clínico', icon: FiFileText },
  { id: 'trabajo', label: 'Plan de Trabajo', icon: FiTarget },
  { id: 'tratamiento', label: 'Plan de tratamiento', icon: FiLayers },
  { id: 'resumen', label: 'Resumen', icon: FiEdit3 },
  { id: 'fotos', label: 'Fotografías', icon: FiCamera },
];

export const selectOptions = ['Seleccionar', 'Normal', 'Alterado', 'Pendiente'];